### ISSUE TITLE
Error when I run with 2take1 menu after Dec 12th 2023

### ISSUE THREAD

**Issue by edwardchung0516** [jhowkNx/Heist-Control-V3#5]
Hi bro,this lua shows error when I run it in 2take1 menu new update after Dec 12th 2023.The game just crashes again and again.will you update this lua soon? thank you

**Comment by kippasaurr** [comment]
I get the same issue too

**Comment by Ethanwu0608** [comment]
Me too

**Comment by buxy97** [comment]
Me too, Game crashes after running script

**Comment by Thomasc33** [comment]
fixed by d6d16cb9cd79a063fa1b39cc91ba99802cc31cda
